TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================


LIBRARY_IOC_Linux += mythen
LIB_SRCS += mythen.cpp


# <name>.dbd will be created from <name>Include.dbd
DBD += mythenSupport.dbd


#include $(AREA_DETECTOR)/ADApp/commonDriverMakefile
include $(ADCORE)/ADApp/commonDriverMakefile

#PROD_LIBS += NDFileMagick
#PROD_LIBS += GraphicsMagick++ GraphicsMagickWand GraphicsMagick

#=============================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

